config/routes.rb
Rails.application.routes.draw do
  resources :documents do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :document
end

app/models/document.rb
class Document < ActiveRecord::Base
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comments
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET documents/1/comments
  def index
    @comments = @document.comments
  end

  # GET documents/1/comments/1
  def show
  end

  # GET documents/1/comments/new
  def new
    @comment = @document.comments.build
  end

  # GET documents/1/comments/1/edit
  def edit
  end

  # POST documents/1/comments
  def create
    @comment = @document.comments.build(comment_params)

    if @comment.save
      redirect_to([@comment.document, @comment], notice: 'Comment was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT documents/1/comments/1
  def update
    if @comment.update_attributes(comment_params)
      redirect_to([@comment.document, @comment], notice: 'Comment was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE documents/1/comments/1
  def destroy
    @comment.destroy

    redirect_to document_comments_url(@document)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comments
      @document = Document.find(params[:document_id])
    end

    def set_comment
      @comment = @document.comments.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:document_id, :comment)
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:title, :doc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@comment.document, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :document_id %><br />
    <%= f.number_field :document_id %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', [@comment.document, @comment] %> |
<%= link_to 'Back', document_comments_path(@comment.document) %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Document</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.document_id %></td>
    <td><%= comment.comment %></td>
    <td><%= link_to 'Show', [comment.document, comment] %></td>
    <td><%= link_to 'Edit', edit_document_comment_path(comment.document, comment) %></td>
    <td><%= link_to 'Destroy', [comment.document, comment], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_document_comment_path(params[:document_id]) %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', document_comments_path(@comment.document) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Document:</b>
  <%= @comment.document_id %>
</p>

<p>
  <b>Comment:</b>
  <%= @comment.comment %>
</p>


<%= link_to 'Edit', edit_document_comment_path(@comment.document, @comment) %> |
<%= link_to 'Back', document_comments_path(@comment.document) %>

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :doc %><br>
    <%= f.text_field :doc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Documents</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Doc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.title %></td>
        <td><%= document.doc %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @document.title %>
</p>

<p>
  <strong>Doc:</strong>
  <%= @document.doc %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Postgres</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>